spring:
  config:
    activate:
      on-profile: local

  flyway:
    enabled: false

---
spring:
  config:
    activate:
      on-profile: dev

  flyway:
    enabled: true
    baseline-on-migrate: true

---
spring:
  config:
    activate:
      on-profile: prod

  flyway:
    enabled: true
    baseline-on-migrate: true
