name: packy API Dev Server - CD

on:
  push:
    branches:
      - develop

jobs:
  CD:
    name: Call Reusable Deploy Workflow
    uses: ./.github/workflows/reusable-cd.yml
    with:
      profile: dev
