name: packy API Prod Server - CD

on:
  push:
    branches:
      - main

jobs:
  CD:
    name: Call Reusable Deploy Workflow
    uses: ./.github/workflows/reusable-cd.yml
    with:
      profile: prod
    secrets:
      ACTION_TOKEN: ${{ secrets.ACTION_TOKEN }}
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

#      - name: Update Release
#        uses: release-drafter/release-drafter@v5
#        with:
#          config-name: release-drafter-config.yml
#        env:
#          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
