name: packy API Dev Server - CD

on:
  push:
    branches:
      - develop

jobs:
  CD:
    name: Call Reusable Deploy Workflow
    uses: ./.github/workflows/reusable-cd.yml
    with:
      profile: dev
    secrets:
      ACTION_TOKEN: ${{ secrets.ACTION_TOKEN }}
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
